# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('excerpt_post_id', models.IntegerField(blank=True, null=True)),
                ('wiki_post_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
