# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_topusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='topusersnew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('questioncount', models.IntegerField()),
                ('displayname', models.CharField(max_length=500)),
                ('urlpicture', models.CharField(blank=True, max_length=100, null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tag')),
            ],
        ),
    ]
